version: '3'
services:
  minio:
    image: bitnami/minio:latest
    hostname: minio
    restart: always
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - ./minio:/data
    ports:
      - 9000:9000
      - 9001:9001

  minio-create-bucket:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./02-src-data:/tmp/src-files
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/processed-data;
      /usr/bin/mc mb myminio/src-data;
      /usr/bin/mc policy set public myminio/src-data;
      /usr/bin/mc policy set public myminio/processed-data;
      /usr/bin/mc mirror --overwrite /tmp/src-files/ myminio/src-data;
      
      exit 0;
      "

  web-service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - minio
      - minio-create-bucket



